<a href="https://colab.research.google.com/github/alice99vieira/BCC19AliceVieira/blob/main/Tarefa9AliceVieira.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Alice Vieira

Tarefa (para agora)

Escrever um notebook do Colab para fazer o que pedido a seguir.

Colocar o seu nome na primeira célula do Notebook.

O notebook deve estar com texto explicando o Notebook.

Todos os resultados devem ser mostrados ao executar o notebook.

Coloque no seu repositório do Github o arquivo '.ipynb' contendo o notebook feito por você com o nome "Tarefa9SeuNome.ipynb".

1) Para este item você deverá usar o arquivo com a porcentagem da população brasileira que é analfabeta, dividida por unidade da federação, de 1981 a 2014 (analfabetismo.csv, encontrado na pasta aula5/dados) (dados disponibilizados por Ipeadata).

Faça um gráfico da taxa de analfabetismo em São Paulo em função do tempo (anos).

In [4]:
import pandas as pd
import numpy as np

Analfabetismo = pd.read_csv('https://raw.githubusercontent.com/alice99vieira/BasesComputacionais/bacd478ebcde398e853ef5c700168b98f105d3a3/aula5/dados/analfabetismo.csv')
Analfabetismo

,Ano,Acre,Alagoas,Amazonas,Amapá,Bahia,Ceará,Distrito Federal,Espírito Santo,Goiás,...,Paraná,Rio de Janeiro,Rio Grande do Norte,Rondônia,Roraima,Rio Grande do Sul,Santa Catarina,Sergipe,São Paulo,Tocantins
0,1981,24.771344,48.714720,13.740147,16.864253,36.535406,42.453047,11.212273,22.497828,24.408604,...,20.287721,11.707655,41.634136,20.128014,9.138271,12.830248,12.911638,39.670939,12.523352,NaN
1,1982,20.682421,53.185056,16.232134,12.843550,36.971875,44.385931,9.902721,25.009842,24.515374,...,20.868585,11.605974,39.494989,19.557072,13.383961,13.032632,13.646692,45.435048,12.740826,NaN
2,1983,20.823673,51.491081,10.814711,13.890302,35.278137,42.979866,10.611223,21.918142,22.788413,...,19.946446,10.601789,42.384636,14.922802,5.685683,12.622268,10.795336,40.218682,11.785755,NaN
3,1984,20.964519,51.779179,11.525739,13.939237,34.639949,43.037199,10.191576,21.635366,21.619731,...,18.255011,10.742911,39.565673,13.264554,9.146159,12.520865,11.352639,40.969008,11.688915,NaN
4,1985,22.012728,50.541485,10.735491,12.779264,35.909958,40.910827,10.939660,20.918003,20.665916,...,17.346611,10.110057,40.155873,13.389101,7.023061,11.254618,10.950922,39.226516,10.876103,NaN
5,1986,20.038209,49.338493,10.386775,6.115666,34.258057,37.889773,9.093172,19.312722,20.620190,...,18.292112,9.659202,38.128308,8.011342,4.171013,10.704186,10.592110,43.758777,10.774463,NaN
6,1987,18.602263,45.368776,12.273202,8.341201,32.874988,40.057266,8.080418,19.917673,19.819628,...,16.250495,9.799160,40.065670,13.901822,5.740370,10.773082,8.809834,39.875297,9.991966,NaN
7,1988,15.516986,43.827070,11.068274,8.871261,32.331936,37.242722,7.998441,20.724363,18.249934,...,15.533841,9.564125,36.665888,13.316371,8.921218,10.595577,11.546561,38.844485,9.567218,NaN
8,1989,20.809149,43.616055,10.954597,12.213618,32.408202,38.766226,9.109928,19.278182,19.319343,...,15.024300,9.217095,36.492866,12.199678,9.363089,10.889342,9.111922,36.850851,10.131712,NaN
9,1990,21.434018,43.641072,9.506657,13.770873,33.176801,38.601733,8.601413,18.773985,19.143916,...,14.569829,9.554070,36.538188,13.218516,9.957395,9.735324,10.439684,36.493782,9.163841,NaN
10,1992,14.612541,35.881664,9.088362,12.300157,31.232694,34.590475,8.897637,17.845742,16.398712,...,12.903952,8.276939,30.318938,10.603622,9.712570,8.600312,8.814025,27.347144,8.894618,27.898423
11,1993,19.252309,33.722659,11.384970,12.694916,30.542943,32.663931,8.114118,13.905194,15.516857,...,12.524239,7.760580,29.867811,11.640661,8.967644,8.323134,7.993831,28.636116,8.123875,26.476866
12,1995,15.808212,34.922072,10.210677,10.721625,28.468647,31.590220,6.496811,14.128134,15.128114,...,11.554368,6.832380,29.579951,9.143759,9.168220,7.838574,7.433056,26.210826,7.687246,24.420915
13,1996,17.986118,36.144006,9.386182,12.902537,24.607450,31.153091,6.281007,14.088258,13.276239,...,11.629681,6.344336,28.497701,7.605114,6.939137,7.209314,7.320478,25.270507,7.353756,20.884051
14,1997,18.495426,36.367398,9.504074,11.681121,27.013083,30.940636,6.011890,13.799726,14.236202,...,10.611938,6.559676,27.204109,10.202154,11.859262,7.025360,6.620459,25.357265,6.795782,23.721204
15,1998,14.494080,34.765723,8.449936,9.128554,24.945686,29.676498,5.562563,12.046664,13.057630,...,10.447197,5.932186,26.680847,7.583822,8.269317,6.815661,6.436478,24.074298,6.574873,22.014916
16,1999,15.648803,32.731338,8.751779,9.558898,24.573729,28.044816,5.025915,11.131123,12.538534,...,10.192804,6.017533,25.519635,9.686015,8.728198,6.059261,6.826882,23.942750,6.172834,21.136807
17,2001,16.727218,30.597308,7.742215,7.159616,22.696074,24.603259,5.529615,11.453410,11.669146,...,8.631336,5.639769,24.184897,10.190279,11.480563,6.239075,5.935004,21.427992,5.982166,18.489611
18,2002,12.976261,31.184284,6.329814,6.153191,21.573191,22.460249,5.669912,10.702704,11.285782,...,7.885307,5.146400,22.683338,8.623983,12.052053,6.302325,5.502941,20.247167,5.859890,18.117778
19,2003,16.863655,30.409382,6.608684,9.211489,21.202627,22.573862,4.447258,10.264118,10.894190,...,7.815144,4.666096,23.398374,8.552735,9.668232,5.765894,4.999209,19.153384,5.410402,17.622490
20,2004,18.081260,29.511691,8.993324,8.477015,20.311736,21.630414,4.198681,9.490437,10.691742,...,7.985058,4.865232,22.286940,10.525310,10.697960,5.486766,4.793656,19.378634,5.519433,17.239341
21,2005,21.046924,29.268524,6.686139,7.432909,18.673142,22.440296,4.663439,8.688691,10.219275,...,7.123356,4.877881,21.468149,9.911856,12.530304,5.216105,5.166633,19.673290,5.408622,16.301999
22,2006,17.491623,26.437066,7.832131,5.337006,18.470787,20.489913,3.765681,9.492926,9.602453,...,6.560486,4.249956,21.813821,10.639231,8.813378,5.228838,5.058388,18.219496,4.978411,14.927020
23,2007,15.693886,25.142654,7.940481,7.170333,18.340907,19.016182,3.726885,8.511549,8.800466,...,6.596290,4.391310,19.564678,9.496987,11.001149,4.989008,4.407395,16.768187,4.607750,14.207411
24,2008,14.884067,25.740950,8.812761,4.666691,17.339964,18.922483,4.018080,8.814452,9.307666,...,6.580464,4.441279,19.992647,9.190467,9.685378,4.967388,4.411674,16.874638,4.744586,14.380684
25,2009,16.353971,24.567118,7.312349,3.261077,16.767485,18.412278,3.446968,8.528824,8.605631,...,6.704561,3.968432,18.135669,9.811070,7.755963,4.597348,4.912092,16.291358,4.749337,13.541848
26,2011,14.382577,21.783119,8.353064,7.598437,14.452356,16.490247,3.146767,6.377092,7.180531,...,6.274444,3.672094,15.844018,9.736121,9.623129,4.268295,3.878033,15.981520,3.666845,12.165590
27,2012,13.461716,21.834940,8.269417,6.723025,15.893686,16.274337,3.485900,6.734058,7.292910,...,5.267335,3.789665,16.041607,8.572059,7.391402,4.256847,3.150491,16.307991,3.806804,13.403468
28,2013,14.606067,21.647721,7.337762,5.966746,14.913226,16.722980,3.186502,6.592571,7.055984,...,5.330169,3.736142,17.166137,8.558027,9.806430,4.425117,3.523806,16.929659,3.710134,12.244653
29,2014,13.079072,21.971093,6.204441,4.215737,14.740348,16.284987,2.728544,6.549233,7.682399,...,4.954787,3.206950,16.209008,8.335295,7.468176,4.466359,3.340807,17.145656,3.759459,12.151294